GENERATE_PIPELINES = None
GENERATION_COUNT = None
GENERATE_PIPELINE_ARGS = None
PNG_INFO_EXTRAS = None
OUTPUT_PATH_PREFIX = None
POST_PROCESS = None

def _postProcess(
    _,
):
    pass

def reset(
):
    global GENERATE_PIPELINES
    global GENERATION_COUNT
    global GENERATE_PIPELINE_ARGS
    global PNG_INFO_EXTRAS
    global OUTPUT_PATH_PREFIX
    global POST_PROCESS

    #TODO
    GENERATE_PIPELINES = 10
    GENERATION_COUNT = 20
    GENERATE_PIPELINE_ARGS = 30
    PNG_INFO_EXTRAS = 40
    OUTPUT_PATH_PREFIX = 50
    POST_PROCESS = 60
    return

    GENERATE_PIPELINES = None
    GENERATION_COUNT = 1
    GENERATE_PIPELINE_ARGS = None
    PNG_INFO_EXTRAS = {}
    OUTPUT_PATH_PREFIX = "output"
    POST_PROCESS = _postProcess
